Algoritmo "tabuada while"
// Disciplina   :
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Tayler Henrique e Pedro Xavier
// Data atual  : 02/04/2023
Var
num, r :Real
i :inteiro
Inicio
escreva("digite um número: ")
leia(num)
i:=1
enquanto (i<=10) faca
 r:= num*i
 escreva(r)
 i:=i+1
 fimenquanto
Fimalgoritmo